version: '2'
services:

 config-service:
  build: ./config-service
  ports:
   - "8888:8888"
 
 discovery-service:
  build: ./discovery-service
  ports:
   - "8761:8761"
  depends_on:
   - "config-service"
  
 proxy-service:
  build: ./proxy-service
  ports:
   - "9999:9999"
  depends_on:
   - "config-service"
   - "discovery-service"

 product-service:
  build: ./product-service
  ports:
   - "8080:8080"
  depends_on:
   - "config-service"
   - "discovery-service"
  

  

  



 
